# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 7
    - env: DBTYPE=mysql; MW=1.23.0
      php: 5.5
    - env: DBTYPE=mysql; MW=1.24.0
      php: 5.6
    - env: DBTYPE=sqlite; MW=master; TYPE=coverage
      php: 7
    - env: DBTYPE=sqlite; MW=1.25.6
      php: 5.6

install:
  - travis_retry composer self-update

before_script: bash ./tests/travis/before_script.sh

script: bash ./tests/travis/script.sh

after_success: bash ./tests/travis/after_success.sh

cache:
  directories:
    - $HOME/.composer/cache
